/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_hanaone_jni_JNIHanaone */

#ifndef _Included_com_hanaone_jni_JNIHanaone
#define _Included_com_hanaone_jni_JNIHanaone
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_hanaone_jni_JNIHanaone
 * Method:    stringFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_hanaone_jni_JNIHanaone_stringFromJNI
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
