/* DO NOT EDIT THIS FILE - it is machine generated */
#include "com_hanaone_jni_JNIHanaone.h"
/* Header for class com_hanaone_jni_JNIHanaone */



JNIEXPORT jstring JNICALL Java_com_hanaone_jni_JNIHanaone_stringFromJNI
  (JNIEnv *jenv, jobject)
{
	jstring url = jenv->NewStringUTF("https://drive.google.com/uc?export=download&id=0Byaz20I0WF7YLUJZTkc2SnA3YVk");
	return url;
}
